name: fam_bud_plann
description: Мобільний застосунок «Планувальник сімейного бюджету»
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  reorderable_grid_view: ^2.2.8
  nfc_manager: ^4.0.2
  http: ^1.4.0
  google_maps_flutter: ^2.12.2
  restart_app: ^1.3.2
  animations: ^2.0.11
  flutter_dotenv: ^6.0.0

  # Сервер
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5

  # Локальна
  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.32
  path_provider: ^2.1.5
  path: ^1.9.1

  # Шифрування
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4

  # Аутентифікація
  google_sign_in: ^6.3.0
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3

  image_picker: ^1.1.2

  # Утиліти
  provider: ^6.1.5
  intl: ^0.20.2
  uuid: ^4.5.1
  device_info_plus: ^9.1.1
  geolocator: ^14.0.0
  share_plus: ^7.2.1

  # UI
  flutter_svg: ^2.1.0
  fl_chart: ^1.0.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  generate: true